name: Publish to Azure WebApps

on: 
  workflow_dispatch: 
  push: 
    branches: 
      main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore ./NewApp.sln

      - name: Build
        run: dotnet build ./NewApp.sln --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./NewApp.sln --configuration Release --no-build
